#!/usr/bin/env bash
#
# Create a bash script using a template.

[[ $1 ]] || exit 1

printf '%s' "\
#!/usr/bin/env bash
#
# $1${2:+ - $2}

help() {
cat <<"HELP"
Usage: $1 [ARGS]
HELP
exit 1
}

if [[ -z "'$1'" ]]; then
  help
elif [[ -n "'$1'" ]]; then
  case "'$1'" in
    "'-1'" | "'--one'") command; exit 0;;
    "'-2'" | "'--two'") command; exit 0;;
  esac
fi

" > "$SCRIPTS/$1" && chmod +x "$SCRIPTS/$1"
