#!/usr/bin/env sh
#
# nwrap - main config for launching `nnn`

export NNN_BMS=""
export NNN_USE_EDITOR=1
export NNN_OPENER="vim"
export LC_COLLATE="C"
alias ncp="cat ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection | tr '\0' '\n'"

nnn -SHd "$@"
