#!/usr/bin/env bash
#
# subs - get subtitles for video then open with mpv

help() {
cat <<HELP
Usage: subs [VIDEO]
HELP
exit 1
}

if [[ -z $1 ]]; then
  help
elif [[ -n $1 ]]; then
  subliminal download -l en "$1"
  mpv "$1"
fi

